# Generated by Django 3.0.4 on 2020-04-24 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('RecNo', models.AutoField(primary_key=True, serialize=False)),
                ('MaintenanceYears', models.PositiveIntegerField()),
                ('TotalServices', models.PositiveIntegerField()),
                ('LastServiceDate', models.DateField()),
                ('NoOfSrvcsDone', models.PositiveIntegerField()),
                ('AMCQuantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'AMC',
                'db_table': 'AMC',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('GSTNo', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=30)),
                ('PhoneN', models.PositiveIntegerField(default=None)),
                ('Location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Shop',
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='Supplier_detail',
            fields=[
                ('GSTSupplier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=20)),
                ('ContactNo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
            ],
            options={
                'verbose_name_plural': 'Supplier_detail',
                'db_table': 'Supplier_detail',
            },
        ),
        migrations.CreateModel(
            name='Supplier_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfSale', models.DateField()),
                ('TotalAmt', models.PositiveIntegerField()),
                ('Paid_Amt', models.PositiveIntegerField()),
                ('GST_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Supplier_detail')),
            ],
            options={
                'verbose_name_plural': 'Supplier_transaction',
                'db_table': 'Supplier_transaction',
                'unique_together': {('GST_No', 'DateOfSale')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=10)),
                ('Brand', models.CharField(max_length=10)),
                ('P_Name', models.CharField(max_length=50)),
                ('Features', models.CharField(max_length=100)),
                ('GSTAmt', models.PositiveIntegerField()),
                ('TotalPrice', models.PositiveIntegerField()),
                ('TotalQuantity', models.PositiveIntegerField()),
                ('GSTnoShop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyt.Shop')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'Product',
                'unique_together': {('ProductId', 'Brand')},
            },
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('Empid', models.AutoField(primary_key=True, serialize=False)),
                ('E_FName', models.CharField(max_length=15)),
                ('E_LName', models.CharField(max_length=15)),
                ('AadharNo', models.PositiveIntegerField()),
                ('JoinDate', models.DateField()),
                ('Qualification', models.CharField(max_length=20)),
                ('PhoneNo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('Salary', models.PositiveIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('GSTnoShop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyt.Shop')),
            ],
            options={
                'verbose_name_plural': 'Employee_Details',
                'db_table': 'Employee_Details',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_Id', models.AutoField(primary_key=True, serialize=False)),
                ('C_Fname', models.CharField(max_length=20)),
                ('C_Lname', models.CharField(max_length=20)),
                ('PhoneNumber', models.PositiveIntegerField()),
                ('CustAddress', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Customer',
                'db_table': 'Customer',
                'unique_together': {('C_Id', 'C_Fname')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('B_Id', models.AutoField(primary_key=True, serialize=False)),
                ('BDate', models.DateField()),
                ('TotalAmt', models.PositiveIntegerField()),
                ('PaidAmt', models.PositiveIntegerField()),
                ('PaymentMode', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'CreditCard'), ('BHIM', 'BHIM')], default='Cash', max_length=10)),
                ('Cust_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Customer')),
            ],
            options={
                'verbose_name_plural': 'Bill',
                'db_table': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('pro_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Product')),
                ('supp_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Supplier_transaction')),
            ],
            options={
                'verbose_name_plural': 'Supplies',
                'db_table': 'Supplies',
                'unique_together': {('supp_info', 'pro_info')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_purchase', models.PositiveIntegerField()),
                ('Rec_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyt.AMC')),
                ('bill_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Bill')),
                ('prod_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Product')),
            ],
            options={
                'verbose_name_plural': 'Purchase',
                'db_table': 'Purchase',
                'unique_together': {('bill_info', 'prod_info')},
            },
        ),
    ]
