# Generated by Django 3.0.4 on 2020-04-24 14:20

import django.core.validators
from django.db import migrations, models
import pyt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pyt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee_details',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier_detail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplies',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee_details',
            name='GSTnoShop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='GSTnoShop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='TotalQuantity',
        ),
        migrations.AlterField(
            model_name='amc',
            name='LastServiceDate',
            field=models.DateField(validators=[pyt.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='amc',
            name='MaintenanceYears',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BDate',
            field=models.DateField(validators=[pyt.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PaidAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='TotalAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')]),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='JoinDate',
            field=models.DateField(validators=[pyt.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='PhoneNo',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')]),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Salary',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='product',
            name='GSTAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='product',
            name='TotalPrice',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='supplier_detail',
            name='ContactNo',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')]),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='DateOfSale',
            field=models.DateField(validators=[pyt.validators.datevalid]),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='Paid_Amt',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='TotalAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg]),
        ),
        migrations.AlterModelTable(
            name='amc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employee_details',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purchase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supplier_detail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supplies',
            table=None,
        ),
    ]
