# Generated by Django 3.0.4 on 2020-04-25 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pyt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pyt', '0003_auto_20200424_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='AMCQuantity',
            field=models.PositiveIntegerField(verbose_name='AMCQuantity'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='LastServiceDate',
            field=models.DateField(validators=[pyt.validators.datevalid], verbose_name='LastServiceDate'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='MaintenanceYears',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='MaintenanceYears'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='NoOfSrvcsDone',
            field=models.PositiveIntegerField(verbose_name='NoOfSrvcsDone'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='RecNo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='RecNo'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='TotalServices',
            field=models.PositiveIntegerField(verbose_name='TotalServices'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BDate',
            field=models.DateField(validators=[pyt.validators.datevalid], verbose_name='BDate'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='B_Id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='B_Id'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Cust_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Customer', verbose_name='Cust_Id'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PaidAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='PaidAmt'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='PaymentMode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'CreditCard'), ('BHIM', 'BHIM')], default='Cash', max_length=10, verbose_name='PaymentMode'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='TotalAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='TotalAmt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='C_Fname',
            field=models.CharField(max_length=20, verbose_name='C_Fname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='C_Id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='C_Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='C_Lname',
            field=models.CharField(max_length=20, verbose_name='C_Lname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CustAddress',
            field=models.CharField(default='', max_length=50, verbose_name='CustAddress'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='AadharNo',
            field=models.PositiveIntegerField(verbose_name='AadharNo'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='E_FName',
            field=models.CharField(max_length=15, verbose_name='E_FName'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='E_LName',
            field=models.CharField(max_length=15, verbose_name='E_LName'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Empid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Empid'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='JoinDate',
            field=models.DateField(validators=[pyt.validators.datevalid], verbose_name='JoinDate'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='PhoneNo',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='PhoneNo'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Qualification',
            field=models.CharField(max_length=20, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Salary',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=10, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Features',
            field=models.CharField(max_length=100, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='GSTAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='GSTAmt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='P_Name',
            field=models.CharField(max_length=50, verbose_name='P_Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductId',
            field=models.CharField(max_length=10, verbose_name='ProductId'),
        ),
        migrations.AlterField(
            model_name='product',
            name='TotalPrice',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='TotalPrice'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Quantity_purchase',
            field=models.PositiveIntegerField(verbose_name='Quantity_purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Rec_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyt.AMC', verbose_name='Rec_no'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Bill', verbose_name='bill_info'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='prod_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Product', verbose_name='prod_info'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='GSTNo',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, verbose_name='GSTNo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='PhoneN',
            field=models.PositiveIntegerField(default=None, verbose_name='PhoneN'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='S_Name',
            field=models.CharField(max_length=30, verbose_name='S_Name'),
        ),
        migrations.AlterField(
            model_name='supplier_detail',
            name='ContactNo',
            field=models.PositiveIntegerField(validators=[pyt.validators.nonneg, django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number'), django.core.validators.MinValueValidator(1000000000, 'Invalid Phone Number')], verbose_name='ContactNo'),
        ),
        migrations.AlterField(
            model_name='supplier_detail',
            name='GSTSupplier',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='GSTSupplier'),
        ),
        migrations.AlterField(
            model_name='supplier_detail',
            name='S_Name',
            field=models.CharField(max_length=20, verbose_name='S_Name'),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='DateOfSale',
            field=models.DateField(validators=[pyt.validators.datevalid], verbose_name='DateOfSale'),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='GST_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Supplier_detail', verbose_name='GST_No'),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='Paid_Amt',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='Paid_Amt'),
        ),
        migrations.AlterField(
            model_name='supplier_transaction',
            name='TotalAmt',
            field=models.FloatField(validators=[pyt.validators.nonneg], verbose_name='TotalAmt'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='Quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='pro_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Product', verbose_name='pro_info'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='supp_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyt.Supplier_transaction', verbose_name='supp_info'),
        ),
    ]
