# Generated by Django 3.0.4 on 2020-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyt', '0004_auto_20200425_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
