# Generated by Django 3.0.4 on 2020-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyt', '0005_purchase_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
